from enum import Enum

class NeighbourSelectionMode(str, Enum):
    RANDOM = "RANDOM",
    NEAREST = "NEAREST",
    FARTHEST = "FARTHEST",
    LEAST_ORIENTATION_DIFFERENCE = "LEAST_ORIENTATION_DIFFERENCE",
    HIGHEST_ORIENTATION_DIFFERENCE = "HIGHEST_ORIENTATION_DIFFERENCE",
    ALL = "ALL"